
#ifndef __IC_BUTTON_MAP_H__
#define __IC_BUTTON_MAP_H__


#ifdef WIN32
#include <windows.h>
#endif

enum icAxisMap
{
    ICAXIS_MOUSE_X      =0,
    ICAXIS_MOUSE_Y      =1,
    ICAXIS_MOUSE_Z      =2,
};

enum icButtonMap
{
#if defined(WIN32)
    ICMOUSE_L           =VK_LBUTTON,
    ICMOUSE_R           =VK_RBUTTON,
    ICMOUSE_M           =VK_MBUTTON,
    ICMOUSE_X1          =VK_XBUTTON1,
    ICMOUSE_X2          =VK_XBUTTON2,

    ICKEY_BACK          =VK_BACK,
    ICKEY_TAB           =VK_TAB,
    ICKEY_CLEAR         =VK_CLEAR,
    ICKEY_RETURN        =VK_RETURN,
    ICKEY_SHIFT         =VK_SHIFT,
    ICKEY_CONTROL       =VK_CONTROL,
    ICKEY_MENU          =VK_MENU,
    ICKEY_PAUSE         =VK_PAUSE,
    ICKEY_CAPS_LOCK     =VK_CAPITAL,
    ICKEY_ESCAPE        =VK_ESCAPE,
    ICKEY_SPACE         =VK_SPACE,
    ICKEY_PG_UP         =VK_PRIOR,
    ICKEY_PG_DN         =VK_NEXT,
    ICKEY_END           =VK_END,
    ICKEY_HOME          =VK_HOME,
    ICKEY_LEFT          =VK_LEFT,
    ICKEY_RIGHT         =VK_RIGHT,
    ICKEY_UP            =VK_UP,
    ICKEY_DOWN          =VK_DOWN,
    ICKEY_SELECT        =VK_SELECT,
    ICKEY_PRINT         =VK_PRINT,
    ICKEY_INSERT        =VK_INSERT,
    ICKEY_DELETE        =VK_DELETE,

    ICKEY_0             =0x30,
    ICKEY_1             =0x31,
    ICKEY_2             =0x32,
    ICKEY_3             =0x33,
    ICKEY_4             =0x34,
    ICKEY_5             =0x35,
    ICKEY_6             =0x36,
    ICKEY_7             =0x37,
    ICKEY_8             =0x38,
    ICKEY_9             =0x39,

    ICKEY_A             =0x41,
    ICKEY_B             =0x42,
    ICKEY_C             =0x43,
    ICKEY_D             =0x44,
    ICKEY_E             =0x45,
    ICKEY_F             =0x46,
    ICKEY_G             =0x47,
    ICKEY_H             =0x48,
    ICKEY_I             =0x49,
    ICKEY_J             =0x4A,
    ICKEY_K             =0x4B,
    ICKEY_L             =0x4C,
    ICKEY_M             =0x4D,
    ICKEY_N             =0x4E,
    ICKEY_O             =0x4F,
    ICKEY_P             =0x50,
    ICKEY_Q             =0x51,
    ICKEY_R             =0x52,
    ICKEY_S             =0x53,
    ICKEY_T             =0x54,
    ICKEY_U             =0x55,
    ICKEY_V             =0x56,
    ICKEY_W             =0x57,
    ICKEY_X             =0x58,
    ICKEY_Y             =0x59,
    ICKEY_Z             =0x5A,

    ICKEY_LWIN          =VK_LWIN,
    ICKEY_RWIN          =VK_RWIN,
    ICKEY_APPS          =VK_APPS,
    ICKEY_SLEEP         =VK_SLEEP,

    ICKEY_NUMP0         =VK_NUMPAD0,
    ICKEY_NUMP1         =VK_NUMPAD1,
    ICKEY_NUMP2         =VK_NUMPAD2,
    ICKEY_NUMP3         =VK_NUMPAD3,
    ICKEY_NUMP4         =VK_NUMPAD4,
    ICKEY_NUMP5         =VK_NUMPAD5,
    ICKEY_NUMP6         =VK_NUMPAD6,
    ICKEY_NUMP7         =VK_NUMPAD7,
    ICKEY_NUMP8         =VK_NUMPAD8,
    ICKEY_NUMP9         =VK_NUMPAD9,

    ICKEY_MULTIPLY      =VK_MULTIPLY,
    ICKEY_ADD           =VK_ADD,
    ICKEY_SEPARATOR     =VK_SEPARATOR,
    ICKEY_SUBTRACT      =VK_SUBTRACT,
    ICKEY_DECIMAL       =VK_DECIMAL,
    ICKEY_DIVIDE        =VK_DIVIDE,

    ICKEY_F1            =VK_F1,
    ICKEY_F2            =VK_F2,
    ICKEY_F3            =VK_F3,
    ICKEY_F4            =VK_F4,
    ICKEY_F5            =VK_F5,
    ICKEY_F6            =VK_F6,
    ICKEY_F7            =VK_F7,
    ICKEY_F8            =VK_F8,
    ICKEY_F9            =VK_F9,
    ICKEY_F10           =VK_F10,
    ICKEY_F11           =VK_F11,
    ICKEY_F12           =VK_F12,
    ICKEY_F13           =VK_F13,
    ICKEY_F14           =VK_F14,
    ICKEY_F15           =VK_F15,
    ICKEY_F16           =VK_F16,
    ICKEY_F17           =VK_F17,
    ICKEY_F18           =VK_F18,
    ICKEY_F19           =VK_F19,
    ICKEY_F20           =VK_F20,
    ICKEY_F21           =VK_F21,
    ICKEY_F22           =VK_F22,
    ICKEY_F23           =VK_F23,
    ICKEY_F24           =VK_F24,

    ICKEY_NUMLOCK       =VK_NUMLOCK,
    ICKEY_SCROLL        =VK_SCROLL,
    ICKEY_LSHIFT        =VK_LSHIFT,
    ICKEY_RSHIFT        =VK_RSHIFT,
    ICKEY_LCONTROL      =VK_LCONTROL,
    ICKEY_RCONTROL      =VK_RCONTROL,
    ICKEY_LALT          =VK_LMENU,
    ICKEY_RALT          =VK_RMENU,

    ICKEY_BROWSER_BACK  =VK_BROWSER_BACK,
    ICKEY_BROWSER_FOR   =VK_BROWSER_FORWARD,
    ICKEY_BROWSER_REF   =VK_BROWSER_REFRESH,
    ICKEY_BROWSER_STOP  =VK_BROWSER_STOP,
    ICKEY_BROWSER_SEAR  =VK_BROWSER_SEARCH,
    ICKEY_BROWSER_FAV   =VK_BROWSER_FAVORITES,
    ICKEY_BROWSER_HOME  =VK_BROWSER_HOME,

    ICKEY_VOL_MUTE      =VK_VOLUME_MUTE,
    ICKEY_VOL_DOWN      =VK_VOLUME_DOWN,
    ICKEY_VOL_UP        =VK_VOLUME_UP,

    ICKEY_MEDIA_NEXT    =VK_MEDIA_NEXT_TRACK,
    ICKEY_MEDIA_PREV    =VK_MEDIA_PREV_TRACK,
    ICKEY_MEDIA_STOP    =VK_MEDIA_STOP,
    ICKEY_MEDIA_PLAY    =VK_MEDIA_PLAY_PAUSE,

    ICKEY_LAUNCH_MAIL   =VK_LAUNCH_MAIL,
    ICKEY_LAUNCH_MEDIA  =VK_LAUNCH_MEDIA_SELECT,
    ICKEY_LAUNCH_APP1   =VK_LAUNCH_APP1,
    ICKEY_LAUNCH_APP2   =VK_LAUNCH_APP2,

    ICKEY_COLON         =VK_OEM_1,
    ICKEY_PLUS          =VK_OEM_PLUS,
    ICKEY_COMMA         =VK_OEM_COMMA,
    ICKEY_MINUS         =VK_OEM_MINUS,
    ICKEY_PERIOD        =VK_OEM_PERIOD,

    ICKEY_QUESTION      =VK_OEM_2,
    ICKEY_TILDE         =VK_OEM_3,
    ICKEY_OPEN_BRACE    =VK_OEM_4,
    ICKEY_SLASH_PIPE    =VK_OEM_5,
    ICKEY_CLOSE_BRACE   =VK_OEM_6,
    ICKEY_QUOTE         =VK_OEM_7,

    ICKEY_MISC1         =VK_OEM_8
#else
    ICMOUSE_L =0,
    ICMOUSE_R,
    ICMOUSE_M,
    ICMOUSE_X1,
    ICMOUSE_X2,

    ICKEY_BACK,
    ICKEY_TAB,
    ICKEY_CLEAR,
    ICKEY_RETURN,
    ICKEY_SHIFT,
    ICKEY_CONTROL,
    ICKEY_MENU,
    ICKEY_PAUSE,
    ICKEY_CAPS_LOCK,
    ICKEY_ESCAPE,
    ICKEY_SPACE,
    ICKEY_PG_UP,
    ICKEY_PG_DN,
    ICKEY_END,
    ICKEY_HOME,
    ICKEY_LEFT,
    ICKEY_RIGHT,
    ICKEY_UP,
    ICKEY_DOWN,
    ICKEY_SELECT,
    ICKEY_PRINT,
    ICKEY_INSERT,
    ICKEY_DELETE,

    ICKEY_0,
    ICKEY_1,
    ICKEY_2,
    ICKEY_3,
    ICKEY_4,
    ICKEY_5,
    ICKEY_6,
    ICKEY_7,
    ICKEY_8,
    ICKEY_9,

    ICKEY_A,
    ICKEY_B,
    ICKEY_C,
    ICKEY_D,
    ICKEY_E,
    ICKEY_F,
    ICKEY_G,
    ICKEY_H,
    ICKEY_I,
    ICKEY_J,
    ICKEY_K,
    ICKEY_L,
    ICKEY_M,
    ICKEY_N,
    ICKEY_O,
    ICKEY_P,
    ICKEY_Q,
    ICKEY_R,
    ICKEY_S,
    ICKEY_T,
    ICKEY_U,
    ICKEY_V,
    ICKEY_W,
    ICKEY_X,
    ICKEY_Y,
    ICKEY_Z,

    ICKEY_LWIN,
    ICKEY_RWIN,
    ICKEY_APPS,
    ICKEY_SLEEP,

    ICKEY_NUMP0,
    ICKEY_NUMP1,
    ICKEY_NUMP2,
    ICKEY_NUMP3,
    ICKEY_NUMP4,
    ICKEY_NUMP5,
    ICKEY_NUMP6,
    ICKEY_NUMP7,
    ICKEY_NUMP8,
    ICKEY_NUMP9,

    ICKEY_MULTIPLY,
    ICKEY_ADD,
    ICKEY_SEPARATOR,
    ICKEY_SUBTRACT,
    ICKEY_DECIMAL,
    ICKEY_DIVIDE,

    ICKEY_F1,
    ICKEY_F2,
    ICKEY_F3,
    ICKEY_F4,
    ICKEY_F5,
    ICKEY_F6,
    ICKEY_F7,
    ICKEY_F8,
    ICKEY_F9,
    ICKEY_F10,
    ICKEY_F11,
    ICKEY_F12,
    ICKEY_F13,
    ICKEY_F14,
    ICKEY_F15,
    ICKEY_F16,
    ICKEY_F17,
    ICKEY_F18,
    ICKEY_F19,
    ICKEY_F20,
    ICKEY_F21,
    ICKEY_F22,
    ICKEY_F23,
    ICKEY_F24,

    ICKEY_NUMLOCK,
    ICKEY_SCROLL,
    ICKEY_LSHIFT,
    ICKEY_RSHIFT,
    ICKEY_LCONTROL,
    ICKEY_RCONTROL,
    ICKEY_LALT,
    ICKEY_RALT,

    ICKEY_BROWSER_BACK,
    ICKEY_BROWSER_FOR,
    ICKEY_BROWSER_REF,
    ICKEY_BROWSER_STOP,
    ICKEY_BROWSER_SEAR,
    ICKEY_BROWSER_FAV,
    ICKEY_BROWSER_HOME,

    ICKEY_VOL_MUTE,
    ICKEY_VOL_DOWN,
    ICKEY_VOL_UP,

    ICKEY_MEDIA_NEXT,
    ICKEY_MEDIA_PREV,
    ICKEY_MEDIA_STOP,
    ICKEY_MEDIA_PLAY,

    ICKEY_LAUNCH_MAIL,
    ICKEY_LAUNCH_MEDIA,
    ICKEY_LAUNCH_APP1,
    ICKEY_LAUNCH_APP2,

    ICKEY_COLON,
    ICKEY_PLUS,
    ICKEY_COMMA,
    ICKEY_MINUS,
    ICKEY_PERIOD,

    ICKEY_QUESTION,
    ICKEY_TILDE,
    ICKEY_OPEN_BRACE,
    ICKEY_SLASH_PIPE,
    ICKEY_CLOSE_BRACE,
    ICKEY_QUOTE,

    ICKEY_MISC1
#endif
};


#endif // __IC_BUTTON_MAP_H__
