
#include "Core/GXDevice/icGLext.h"


bool IsExtensionSupported(const char* szTargetExt, const char* szExtList)
{
	const char *pszStart;
	char *pszWhere, *pszTerminator;

	// Extension names should not have spaces
	pszWhere = (char*)strchr(szTargetExt, ' ');
	if( pszWhere || *szTargetExt == '\0' )
		return false;

	// Search The Extensions String For An Exact Copy
	pszStart = szExtList;
	for(;;)
	{
		pszWhere = (char*)strstr(pszStart, szTargetExt);
		if( !pszWhere )
			break;
		pszTerminator = pszWhere + strlen( szTargetExt );
		if( pszWhere == pszStart || *( pszWhere - 1 ) == ' ' )
			if( *pszTerminator == ' ' || *pszTerminator == '\0' )
				return true;
		pszStart = pszTerminator;
	}
	return false;
}

SWAPINTEXT wglSwapIntervalEXT = NULL;   // Swap Interval EXT


/* ----------------------------- GL_VERSION_1_2 ---------------------------- */
#ifdef IC_GL_VERSION_1_2

PFNGLCOPYTEXSUBIMAGE3D glCopyTexSubImage3D = NULL;
PFNGLDRAWRANGEELEMENTS glDrawRangeElements = NULL;
PFNGLTEXIMAGE3D glTexImage3D = NULL;
PFNGLTEXSUBIMAGE3D glTexSubImage3D = NULL;

#endif //IC_GL_VERSION_1_2
/* ----------------------------- GL_VERSION_1_3 ---------------------------- */
#ifdef IC_GL_VERSION_1_3

PFNGLACTIVETEXTURE glActiveTexture = NULL;
PFNGLCLIENTACTIVETEXTURE glClientActiveTexture = NULL;
PFNGLCOMPRESSEDTEXIMAGE1D glCompressedTexImage1D = NULL;
PFNGLCOMPRESSEDTEXIMAGE2D glCompressedTexImage2D = NULL;
PFNGLCOMPRESSEDTEXIMAGE3D glCompressedTexImage3D = NULL;
PFNGLCOMPRESSEDTEXSUBIMAGE1D glCompressedTexSubImage1D = NULL;
PFNGLCOMPRESSEDTEXSUBIMAGE2D glCompressedTexSubImage2D = NULL;
PFNGLCOMPRESSEDTEXSUBIMAGE3D glCompressedTexSubImage3D = NULL;
PFNGLGETCOMPRESSEDTEXIMAGE glGetCompressedTexImage = NULL;
PFNGLLOADTRANSPOSEMATRIXD glLoadTransposeMatrixd = NULL;
PFNGLLOADTRANSPOSEMATRIXF glLoadTransposeMatrixf = NULL;
PFNGLMULTTRANSPOSEMATRIXD glMultTransposeMatrixd = NULL;
PFNGLMULTTRANSPOSEMATRIXF glMultTransposeMatrixf = NULL;
PFNGLMULTITEXCOORD1D glMultiTexCoord1d = NULL;
PFNGLMULTITEXCOORD1DV glMultiTexCoord1dv = NULL;
PFNGLMULTITEXCOORD1F glMultiTexCoord1f = NULL;
PFNGLMULTITEXCOORD1FV glMultiTexCoord1fv = NULL;
PFNGLMULTITEXCOORD1I glMultiTexCoord1i = NULL;
PFNGLMULTITEXCOORD1IV glMultiTexCoord1iv = NULL;
PFNGLMULTITEXCOORD1S glMultiTexCoord1s = NULL;
PFNGLMULTITEXCOORD1SV glMultiTexCoord1sv = NULL;
PFNGLMULTITEXCOORD2D glMultiTexCoord2d = NULL;
PFNGLMULTITEXCOORD2DV glMultiTexCoord2dv = NULL;
PFNGLMULTITEXCOORD2F glMultiTexCoord2f = NULL;
PFNGLMULTITEXCOORD2FV glMultiTexCoord2fv = NULL;
PFNGLMULTITEXCOORD2I glMultiTexCoord2i = NULL;
PFNGLMULTITEXCOORD2IV glMultiTexCoord2iv = NULL;
PFNGLMULTITEXCOORD2S glMultiTexCoord2s = NULL;
PFNGLMULTITEXCOORD2SV glMultiTexCoord2sv = NULL;
PFNGLMULTITEXCOORD3D glMultiTexCoord3d = NULL;
PFNGLMULTITEXCOORD3DV glMultiTexCoord3dv = NULL;
PFNGLMULTITEXCOORD3F glMultiTexCoord3f = NULL;
PFNGLMULTITEXCOORD3FV glMultiTexCoord3fv = NULL;
PFNGLMULTITEXCOORD3I glMultiTexCoord3i = NULL;
PFNGLMULTITEXCOORD3IV glMultiTexCoord3iv = NULL;
PFNGLMULTITEXCOORD3S glMultiTexCoord3s = NULL;
PFNGLMULTITEXCOORD3SV glMultiTexCoord3sv = NULL;
PFNGLMULTITEXCOORD4D glMultiTexCoord4d = NULL;
PFNGLMULTITEXCOORD4DV glMultiTexCoord4dv = NULL;
PFNGLMULTITEXCOORD4F glMultiTexCoord4f = NULL;
PFNGLMULTITEXCOORD4FV glMultiTexCoord4fv = NULL;
PFNGLMULTITEXCOORD4I glMultiTexCoord4i = NULL;
PFNGLMULTITEXCOORD4IV glMultiTexCoord4iv = NULL;
PFNGLMULTITEXCOORD4S glMultiTexCoord4s = NULL;
PFNGLMULTITEXCOORD4SV glMultiTexCoord4sv = NULL;
PFNGLSAMPLECOVERAGE glSampleCoverage = NULL;

#endif //IC_GL_VERSION_1_3
/* ----------------------------- GL_VERSION_1_4 ---------------------------- */
#ifdef IC_GL_VERSION_1_4

PFNGLBLENDCOLOR glBlendColor = NULL;
PFNGLBLENDEQUATION glBlendEquation = NULL;
PFNGLBLENDFUNCSEPARATE glBlendFuncSeparate = NULL;
PFNGLFOGCOORDPOINTER glFogCoordPointer = NULL;
PFNGLFOGCOORDD glFogCoordd = NULL;
PFNGLFOGCOORDDV glFogCoorddv = NULL;
PFNGLFOGCOORDF glFogCoordf = NULL;
PFNGLFOGCOORDFV glFogCoordfv = NULL;
PFNGLMULTIDRAWARRAYS glMultiDrawArrays = NULL;
PFNGLMULTIDRAWELEMENTS glMultiDrawElements = NULL;
PFNGLPOINTPARAMETERF glPointParameterf = NULL;
PFNGLPOINTPARAMETERFV glPointParameterfv = NULL;
PFNGLSECONDARYCOLOR3B glSecondaryColor3b = NULL;
PFNGLSECONDARYCOLOR3BV glSecondaryColor3bv = NULL;
PFNGLSECONDARYCOLOR3D glSecondaryColor3d = NULL;
PFNGLSECONDARYCOLOR3DV glSecondaryColor3dv = NULL;
PFNGLSECONDARYCOLOR3F glSecondaryColor3f = NULL;
PFNGLSECONDARYCOLOR3FV glSecondaryColor3fv = NULL;
PFNGLSECONDARYCOLOR3I glSecondaryColor3i = NULL;
PFNGLSECONDARYCOLOR3IV glSecondaryColor3iv = NULL;
PFNGLSECONDARYCOLOR3S glSecondaryColor3s = NULL;
PFNGLSECONDARYCOLOR3SV glSecondaryColor3sv = NULL;
PFNGLSECONDARYCOLOR3UB glSecondaryColor3ub = NULL;
PFNGLSECONDARYCOLOR3UBV glSecondaryColor3ubv = NULL;
PFNGLSECONDARYCOLOR3UI glSecondaryColor3ui = NULL;
PFNGLSECONDARYCOLOR3UIV glSecondaryColor3uiv = NULL;
PFNGLSECONDARYCOLOR3US glSecondaryColor3us = NULL;
PFNGLSECONDARYCOLOR3USV glSecondaryColor3usv = NULL;
PFNGLSECONDARYCOLORPOINTER glSecondaryColorPointer = NULL;
PFNGLWINDOWPOS2D glWindowPos2d = NULL;
PFNGLWINDOWPOS2DV glWindowPos2dv = NULL;
PFNGLWINDOWPOS2F glWindowPos2f = NULL;
PFNGLWINDOWPOS2FV glWindowPos2fv = NULL;
PFNGLWINDOWPOS2I glWindowPos2i = NULL;
PFNGLWINDOWPOS2IV glWindowPos2iv = NULL;
PFNGLWINDOWPOS2S glWindowPos2s = NULL;
PFNGLWINDOWPOS2SV glWindowPos2sv = NULL;
PFNGLWINDOWPOS3D glWindowPos3d = NULL;
PFNGLWINDOWPOS3DV glWindowPos3dv = NULL;
PFNGLWINDOWPOS3F glWindowPos3f = NULL;
PFNGLWINDOWPOS3FV glWindowPos3fv = NULL;
PFNGLWINDOWPOS3I glWindowPos3i = NULL;
PFNGLWINDOWPOS3IV glWindowPos3iv = NULL;
PFNGLWINDOWPOS3S glWindowPos3s = NULL;
PFNGLWINDOWPOS3SV glWindowPos3sv = NULL;
/* ----------------------------- GL_VERSION_1_5 ---------------------------- */
PFNGLBEGINQUERY glBeginQuery = NULL;
PFNGLBINDBUFFER glBindBuffer = NULL;
PFNGLBUFFERDATA glBufferData = NULL;
PFNGLBUFFERSUBDATA glBufferSubData = NULL;
PFNGLDELETEBUFFERS glDeleteBuffers = NULL;
PFNGLDELETEQUERIES glDeleteQueries = NULL;
PFNGLENDQUERY glEndQuery = NULL;
PFNGLGENBUFFERS glGenBuffers = NULL;
PFNGLGENQUERIES glGenQueries = NULL;
PFNGLGETBUFFERPARAMETERIV glGetBufferParameteriv = NULL;
PFNGLGETBUFFERPOINTERV glGetBufferPointerv = NULL;
PFNGLGETBUFFERSUBDATA glGetBufferSubData = NULL;
PFNGLGETQUERYOBJECTIV glGetQueryObjectiv = NULL;
PFNGLGETQUERYOBJECTUIV glGetQueryObjectuiv = NULL;
PFNGLGETQUERYIV glGetQueryiv = NULL;
PFNGLISBUFFER glIsBuffer = NULL;
PFNGLISQUERY glIsQuery = NULL;
PFNGLMAPBUFFER glMapBuffer = NULL;
PFNGLUNMAPBUFFER glUnmapBuffer = NULL;

#endif //IC_GL_VERSION_1_4
/* ----------------------------- GL_VERSION_2_0 ---------------------------- */
#ifdef IC_GL_VERSION_2_0

PFNGLATTACHSHADER glAttachShader = NULL;
PFNGLBINDATTRIBLOCATION glBindAttribLocation = NULL;
PFNGLBLENDEQUATIONSEPARATE glBlendEquationSeparate = NULL;
PFNGLCOMPILESHADER glCompileShader = NULL;
PFNGLCREATEPROGRAM glCreateProgram = NULL;
PFNGLCREATESHADER glCreateShader = NULL;
PFNGLDELETEPROGRAM glDeleteProgram = NULL;
PFNGLDELETESHADER glDeleteShader = NULL;
PFNGLDETACHSHADER glDetachShader = NULL;
PFNGLDISABLEVERTEXATTRIBARRAY glDisableVertexAttribArray = NULL;
PFNGLDRAWBUFFERS glDrawBuffers = NULL;
PFNGLENABLEVERTEXATTRIBARRAY glEnableVertexAttribArray = NULL;
PFNGLGETACTIVEATTRIB glGetActiveAttrib = NULL;
PFNGLGETACTIVEUNIFORM glGetActiveUniform = NULL;
PFNGLGETATTACHEDSHADERS glGetAttachedShaders = NULL;
PFNGLGETATTRIBLOCATION glGetAttribLocation = NULL;
PFNGLGETPROGRAMINFOLOG glGetProgramInfoLog = NULL;
PFNGLGETPROGRAMIV glGetProgramiv = NULL;
PFNGLGETSHADERINFOLOG glGetShaderInfoLog = NULL;
PFNGLGETSHADERSOURCE glGetShaderSource = NULL;
PFNGLGETSHADERIV glGetShaderiv = NULL;
PFNGLGETUNIFORMLOCATION glGetUniformLocation = NULL;
PFNGLGETUNIFORMFV glGetUniformfv = NULL;
PFNGLGETUNIFORMIV glGetUniformiv = NULL;
PFNGLGETVERTEXATTRIBPOINTERV glGetVertexAttribPointerv = NULL;
PFNGLGETVERTEXATTRIBDV glGetVertexAttribdv = NULL;
PFNGLGETVERTEXATTRIBFV glGetVertexAttribfv = NULL;
PFNGLGETVERTEXATTRIBIV glGetVertexAttribiv = NULL;
PFNGLISPROGRAM glIsProgram = NULL;
PFNGLISSHADER glIsShader = NULL;
PFNGLLINKPROGRAM glLinkProgram = NULL;
PFNGLSHADERSOURCE glShaderSource = NULL;
PFNGLSTENCILFUNCSEPARATE glStencilFuncSeparate = NULL;
PFNGLSTENCILMASKSEPARATE glStencilMaskSeparate = NULL;
PFNGLSTENCILOPSEPARATE glStencilOpSeparate = NULL;
PFNGLUNIFORM1F glUniform1f = NULL;
PFNGLUNIFORM1FV glUniform1fv = NULL;
PFNGLUNIFORM1I glUniform1i = NULL;
PFNGLUNIFORM1IV glUniform1iv = NULL;
PFNGLUNIFORM2F glUniform2f = NULL;
PFNGLUNIFORM2FV glUniform2fv = NULL;
PFNGLUNIFORM2I glUniform2i = NULL;
PFNGLUNIFORM2IV glUniform2iv = NULL;
PFNGLUNIFORM3F glUniform3f = NULL;
PFNGLUNIFORM3FV glUniform3fv = NULL;
PFNGLUNIFORM3I glUniform3i = NULL;
PFNGLUNIFORM3IV glUniform3iv = NULL;
PFNGLUNIFORM4F glUniform4f = NULL;
PFNGLUNIFORM4FV glUniform4fv = NULL;
PFNGLUNIFORM4I glUniform4i = NULL;
PFNGLUNIFORM4IV glUniform4iv = NULL;
PFNGLUNIFORMMATRIX2FV glUniformMatrix2fv = NULL;
PFNGLUNIFORMMATRIX3FV glUniformMatrix3fv = NULL;
PFNGLUNIFORMMATRIX4FV glUniformMatrix4fv = NULL;
PFNGLUSEPROGRAM glUseProgram = NULL;
PFNGLVALIDATEPROGRAM glValidateProgram = NULL;
PFNGLVERTEXATTRIB1D glVertexAttrib1d = NULL;
PFNGLVERTEXATTRIB1DV glVertexAttrib1dv = NULL;
PFNGLVERTEXATTRIB1F glVertexAttrib1f = NULL;
PFNGLVERTEXATTRIB1FV glVertexAttrib1fv = NULL;
PFNGLVERTEXATTRIB1S glVertexAttrib1s = NULL;
PFNGLVERTEXATTRIB1SV glVertexAttrib1sv = NULL;
PFNGLVERTEXATTRIB2D glVertexAttrib2d = NULL;
PFNGLVERTEXATTRIB2DV glVertexAttrib2dv = NULL;
PFNGLVERTEXATTRIB2F glVertexAttrib2f = NULL;
PFNGLVERTEXATTRIB2FV glVertexAttrib2fv = NULL;
PFNGLVERTEXATTRIB2S glVertexAttrib2s = NULL;
PFNGLVERTEXATTRIB2SV glVertexAttrib2sv = NULL;
PFNGLVERTEXATTRIB3D glVertexAttrib3d = NULL;
PFNGLVERTEXATTRIB3DV glVertexAttrib3dv = NULL;
PFNGLVERTEXATTRIB3F glVertexAttrib3f = NULL;
PFNGLVERTEXATTRIB3FV glVertexAttrib3fv = NULL;
PFNGLVERTEXATTRIB3S glVertexAttrib3s = NULL;
PFNGLVERTEXATTRIB3SV glVertexAttrib3sv = NULL;
PFNGLVERTEXATTRIB4NBV glVertexAttrib4Nbv = NULL;
PFNGLVERTEXATTRIB4NIV glVertexAttrib4Niv = NULL;
PFNGLVERTEXATTRIB4NSV glVertexAttrib4Nsv = NULL;
PFNGLVERTEXATTRIB4NUB glVertexAttrib4Nub = NULL;
PFNGLVERTEXATTRIB4NUBV glVertexAttrib4Nubv = NULL;
PFNGLVERTEXATTRIB4NUIV glVertexAttrib4Nuiv = NULL;
PFNGLVERTEXATTRIB4NUSV glVertexAttrib4Nusv = NULL;
PFNGLVERTEXATTRIB4BV glVertexAttrib4bv = NULL;
PFNGLVERTEXATTRIB4D glVertexAttrib4d = NULL;
PFNGLVERTEXATTRIB4DV glVertexAttrib4dv = NULL;
PFNGLVERTEXATTRIB4F glVertexAttrib4f = NULL;
PFNGLVERTEXATTRIB4FV glVertexAttrib4fv = NULL;
PFNGLVERTEXATTRIB4IV glVertexAttrib4iv = NULL;
PFNGLVERTEXATTRIB4S glVertexAttrib4s = NULL;
PFNGLVERTEXATTRIB4SV glVertexAttrib4sv = NULL;
PFNGLVERTEXATTRIB4UBV glVertexAttrib4ubv = NULL;
PFNGLVERTEXATTRIB4UIV glVertexAttrib4uiv = NULL;
PFNGLVERTEXATTRIB4USV glVertexAttrib4usv = NULL;
PFNGLVERTEXATTRIBPOINTER glVertexAttribPointer = NULL;

#endif //IC_GL_VERSION_2_0